### ISSUE TITLE
handleOpenURL doesn't open for opened cordova apps

### ISSUE THREAD

**Issue by murliatdure** [hypery2k/cordova-urlhandler-plugin#6]
handleOpenURL() doesn't gets triggered if the app is already running in background for ios and android also.

Any alternatives to support the same?

**Comment by hypery2k** [comment]
Works for me with iOS and android, even if app is running in background

**Comment by phuzi** [comment]
Just in case anyone else stumbles across this issue. I was having the same problem launching the app from an NFC tag because I omitted the host portion of the URI e.g. `myscheme:/path/to/open`

This is a valid **_URI_** but isn't a valid **_URL_**.

To fix the issue I changed the URI to `myscheme://appname/path/to/open`

Cheers
